import { QRCodeSVG } from "qrcode.react";

export default function VerificationSection({

  report = {},

}) {

  const verificationId =

    report.verification_id ||

    `${report.lab_number}-${report.test_type}`;

  const verificationURL =

    `https://www.pefamedlab.com/verify/${verificationId}`;

  return (

    <section className="verification-section">

      {/* =====================================
          QR CODE
      ====================================== */}

      <div className="verification-qr">

        <QRCodeSVG

          value={verificationURL}

          size={70}

          level="H"

        />

      </div>

      {/* =====================================
          DETAILS
      ====================================== */}

      <div className="verification-details">

        <div className="verification-row">

          <span className="verification-label">

            Verification ID

          </span>

          <span className="verification-value">

            {verificationId}

          </span>

        </div>

        <div className="verification-row">

          <span className="verification-label">

            Released On

          </span>

          <span className="verification-value">

            {

              report.released_at

                ? new Date(

                    report.released_at

                  ).toLocaleString(

                    "en-GB",

                    {

                      day:"2-digit",

                      month:"short",

                      year:"numeric",

                      hour:"2-digit",

                      minute:"2-digit",

                    }

                  )

                : "-"

            }

          </span>

        </div>

        <div className="verification-row">

          <span className="verification-label">

            Status

          </span>

          <span className="verification-status">

            VERIFIED

          </span>

        </div>

      </div>

      {/* =====================================
          NOTICE
      ====================================== */}

      <div className="verification-note">

        This report was electronically generated by

        PEFA Medical Diagnostic Services.

        Scan the QR Code or use the Verification ID

        to confirm authenticity.

      </div>

    </section>

  );

}