import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase";
import { Activity, CalendarDays, Download, Eye, Filter, RefreshCw, Search, ShieldCheck, Users, X } from "lucide-react";
import "../styles/auditTrail.css";

const text=v=>String(v??"").trim();
const fmtDate=v=>v?new Date(v).toLocaleString("en-NG",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";

export default function AuditTrail(){
 const [logs,setLogs]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[role,setRole]=useState("All Roles"),[module,setModule]=useState("All Modules"),[action,setAction]=useState("All Actions"),[date,setDate]=useState("All Time"),[selected,setSelected]=useState(null),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const {data,error}=await supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(5000);if(error)throw error;setLogs(Array.isArray(data)?data:[]);}catch(e){console.error("[AUDIT TRAIL]",e);setError(e?.message||"Unable to load audit trail.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[load]);
 const options=useMemo(()=>({roles:["All Roles",...new Set(logs.map(x=>text(x.user_role)).filter(Boolean))],modules:["All Modules",...new Set(logs.map(x=>text(x.module)).filter(Boolean))],actions:["All Actions",...new Set(logs.map(x=>text(x.action)).filter(Boolean))]}),[logs]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();const now=new Date();return logs.filter(x=>{const d=x.created_at?new Date(x.created_at):null;const dateOk=date==="All Time"||(date==="Today"&&d&&d.toDateString()===now.toDateString())||(date==="7 Days"&&d&&now-d<=7*864e5)||(date==="30 Days"&&d&&now-d<=30*864e5);return dateOk&&(role==="All Roles"||x.user_role===role)&&(module==="All Modules"||x.module===module)&&(action==="All Actions"||x.action===action)&&(!q||[x.user_name,x.user_role,x.module,x.action,x.description].some(v=>text(v).toLowerCase().includes(q)));});},[logs,search,role,module,action,date]);
 const stats=useMemo(()=>{const today=new Date().toDateString();return{total:logs.length,today:logs.filter(x=>x.created_at&&new Date(x.created_at).toDateString()===today).length,users:new Set(logs.map(x=>text(x.user_name)).filter(Boolean)).size,modules:new Set(logs.map(x=>text(x.module)).filter(Boolean)).size}},[logs]);
 const exportCsv=()=>{const rows=filtered.map(x=>[x.created_at,x.user_name,x.user_role,x.module,x.action,x.description]);const csv=[["Time","User","Role","Module","Action","Description"],...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const b=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`PEFA-Audit-Trail-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="audit-page"><header className="audit-hero"><div><span className="audit-kicker">PEFA ENTERPRISE SECURITY</span><h1>Audit Trail</h1><p>Immutable operational visibility across authentication, registration, payment and laboratory workflows.</p></div><div className="audit-actions"><button type="button" onClick={load} disabled={loading}><RefreshCw size={17} className={loading?"audit-spin":""}/>Refresh</button><button type="button" onClick={exportCsv}><Download size={17}/>Export</button></div></header>
 {error&&<div className="audit-alert">{error}</div>}
 <section className="audit-kpis"><div><span><Activity/>Total Events</span><strong>{stats.total.toLocaleString()}</strong><small>Stored audit records</small></div><div><span><CalendarDays/>Today</span><strong>{stats.today.toLocaleString()}</strong><small>Events recorded today</small></div><div><span><Users/>Active Users</span><strong>{stats.users.toLocaleString()}</strong><small>Users represented in logs</small></div><div><span><ShieldCheck/>Modules</span><strong>{stats.modules.toLocaleString()}</strong><small>Operational areas</small></div></section>
 <section className="audit-card audit-filters"><div className="audit-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user, module, action or description..."/></div><div className="audit-filter"><Filter size={15}/><select value={role} onChange={e=>setRole(e.target.value)}>{options.roles.map(x=><option key={x}>{x}</option>)}</select></div><div className="audit-filter"><select value={module} onChange={e=>setModule(e.target.value)}>{options.modules.map(x=><option key={x}>{x}</option>)}</select></div><div className="audit-filter"><select value={action} onChange={e=>setAction(e.target.value)}>{options.actions.map(x=><option key={x}>{x}</option>)}</select></div><div className="audit-filter"><select value={date} onChange={e=>setDate(e.target.value)}><option>All Time</option><option>Today</option><option>7 Days</option><option>30 Days</option></select></div></section>
 <section className="audit-card"><div className="audit-card-head"><div><span>SECURITY EVENT REGISTER</span><h2>Operational Activity</h2></div><b>{filtered.length.toLocaleString()} events</b></div><div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Module</th><th>Action</th><th>Description</th><th></th></tr></thead><tbody>{loading&&!filtered.length?<tr><td colSpan="7" className="audit-empty">Loading audit records...</td></tr>:filtered.length?filtered.map((x,i)=><tr key={x.id||i}><td>{fmtDate(x.created_at)}</td><td><strong>{x.user_name||"Unknown"}</strong></td><td><span className="audit-role">{x.user_role||"—"}</span></td><td>{x.module||"—"}</td><td><span className="audit-action">{x.action||"—"}</span></td><td className="audit-description">{x.description||"—"}</td><td><button type="button" className="audit-view" onClick={()=>setSelected(x)} title="View details"><Eye size={16}/></button></td></tr>):<tr><td colSpan="7" className="audit-empty">No audit events match the selected filters.</td></tr>}</tbody></table></div></section>
 {selected&&<div className="audit-overlay" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="audit-detail"><div className="audit-detail-head"><div><span>AUDIT EVENT</span><h2>{selected.action||"Activity"}</h2></div><button type="button" onClick={()=>setSelected(null)}><X size={19}/></button></div><div className="audit-detail-grid"><div><span>Time</span><strong>{fmtDate(selected.created_at)}</strong></div><div><span>User</span><strong>{selected.user_name||"Unknown"}</strong></div><div><span>Role</span><strong>{selected.user_role||"—"}</strong></div><div><span>Module</span><strong>{selected.module||"—"}</strong></div><div className="wide"><span>Description</span><strong>{selected.description||"—"}</strong></div></div><div className="audit-detail-footer">PEFA Enterprise Audit Trail</div></div></div>}
 </div>;
}
