import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase";
import "../styles/finance.css";
import "../styles/financePremium.css";

const money = (v) => `₦${Number(v || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const startFor = (period) => { const n=new Date(); if(period==="today") return new Date(n.getFullYear(),n.getMonth(),n.getDate()); if(period==="week"){const d=new Date(n);d.setDate(d.getDate()-6);d.setHours(0,0,0,0);return d;} if(period==="month") return new Date(n.getFullYear(),n.getMonth(),1); if(period==="year") return new Date(n.getFullYear(),0,1); return null; };

export default function FinancialReports(){
  const [period,setPeriod]=useState("month"); const [payments,setPayments]=useState([]); const [expenses,setExpenses]=useState([]); const [orders,setOrders]=useState([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const[p,e,o]=await Promise.all([supabase.from("service_payments").select("id, order_id, receipt_number, amount, payment_method, payment_reference, notes, received_by, payment_date, created_at").order("created_at",{ascending:false}).limit(5000),supabase.from("expenses").select("*").order("created_at",{ascending:false}).limit(2000),supabase.from("service_orders").select("id, patient_id, patient_name, lab_number, order_number, total_amount, amount_paid, balance, created_at").order("created_at",{ascending:false}).limit(5000)]);if(p.error)throw p.error;if(e.error)throw e.error;if(o.error)throw o.error;const orderMap=new Map((o.data||[]).map(order=>[String(order.id),order]));const paymentRows=(p.data||[]).map(payment=>{const order=orderMap.get(String(payment.order_id))||{};return {...payment,patient_name:order.patient_name||"",lab_number:order.lab_number||"",display_date:payment.payment_date||payment.created_at};});setPayments(paymentRows);setExpenses(e.data||[]);setOrders(o.data||[]);}catch(e){console.error("[PEFA FINANCIAL REPORTS]",e);setError(e?.message||"Unable to load financial report.");setPayments([]);setExpenses([]);setOrders([]);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const start=startFor(period); const p=useMemo(()=>payments.filter(x=>!start||new Date(x.display_date)>=start),[payments,start]); const ex=useMemo(()=>expenses.filter(x=>!start||new Date(x.expense_date||x.created_at)>=start),[expenses,start]); const income=p.reduce((s,x)=>s+Number(x.amount||0),0),expense=ex.reduce((s,x)=>s+Number(x.amount||0),0),outstanding=orders.reduce((s,x)=>s+Number(x.balance||0),0),profit=income-expense;
  const exportCSV=()=>{const rows=[["Date","Lab Number","Patient","Amount","Method","Reference","Receipt","Cashier"],...p.map(x=>[x.display_date,x.lab_number||"",x.patient_name||"",x.amount||0,x.payment_method||"",x.payment_reference||"",x.receipt_number||"",x.received_by||""])];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`PEFA_Financial_Report_${period}.csv`;a.click();URL.revokeObjectURL(a.href);};
  return <div className="page pefa-finance-page"><div className="pefa-finance-header"><div><span className="pefa-eyebrow">MANAGEMENT REPORTING</span><h1>Financial Reports</h1><p>Period-based report using actual Payment Portal records and the expense register.</p></div><div className="pefa-header-actions"><button type="button" className="pefa-finance-refresh" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button><button type="button" className="pefa-finance-primary" onClick={exportCSV} disabled={!p.length}>Export CSV</button></div></div><div className="pefa-finance-toolbar"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All Time</option><option value="today">Today</option><option value="week">Last 7 Days</option><option value="month">This Month</option><option value="year">This Year</option></select></div>{error&&<div className="pefa-finance-alert">{error}</div>}<div className="pefa-finance-cards"><div><span>Income</span><strong>{money(income)}</strong></div><div><span>Expenses</span><strong>{money(expense)}</strong></div><div><span>Net / Profit</span><strong>{money(profit)}</strong></div><div><span>Outstanding</span><strong>{money(outstanding)}</strong></div></div><div className="pefa-finance-section"><h2>Payment Ledger Summary</h2>{loading?<p>Loading report…</p>:<div className="pefa-table-wrap"><table className="payment-table pefa-finance-table"><thead><tr><th>Date</th><th>Lab No</th><th>Patient</th><th>Amount</th><th>Method</th><th>Reference</th><th>Receipt</th><th>Cashier</th></tr></thead><tbody>{p.length?p.slice(0,500).map(x=><tr key={x.id}><td>{new Date(x.display_date).toLocaleString("en-NG")}</td><td>{x.lab_number||"—"}</td><td><strong>{x.patient_name||"—"}</strong></td><td>{money(x.amount)}</td><td>{x.payment_method||"—"}</td><td>{x.payment_reference||"—"}</td><td>{x.receipt_number||"—"}</td><td>{x.received_by||"—"}</td></tr>):<tr><td colSpan="8" className="pefa-empty">No payments in the selected period.</td></tr>}</tbody></table></div>}</div></div>;
}
